version: 2

sources:
  - name: snowflake_test
    description: 'snowflake sample database'
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCDS_SF10TCL
    tables:
      - name: STORE_SALES
        description: 'sales details'
